Academics/Controllers/InstructorController.cs
using Academic.DataAccess;
using Academics.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace Academics.Controllers
{
    public class InstructorController : Controller
    {


        private readonly AppDbContext _context;
        public InstructorController()
        {

            var context = new AppDbContext();
            _context = context;

        }

        public IActionResult Index(string term="", int currentPage = 1)
        {
            term = string.IsNullOrEmpty(term) ? "" : term.ToLower();
            var ListInstructors = _context.Instructors.Include(x => x.Office).ToList();
            var empData = new PaginatedList<Instructor>();

            var result = (from instructor in ListInstructors
                          where term == "" || instructor.FName.ToLower().StartsWith(term)
                          select new Instructor
                          {
                              FName = instructor.FName,
                              LName = instructor.LName,
                              Id = instructor.Id,
                              OfficeId = instructor.OfficeId,
                              Office = instructor.Office,
                          });



            int totalRecords = result.Count();
            int pageSize = 10;
            int totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);
            result = result.Skip((currentPage - 1) * pageSize).Take(pageSize);

            empData.Entity = result;
            empData.CurrentPage = currentPage;
            empData.TotalPages = totalPages;
            empData.PageSize = pageSize;
            empData.Term=term;


            return View(empData);
        }

        public IActionResult AddInstructor()
        {
            List<Office> officesList = _context.Offices.Where(x => x.OfficeEnabled == true).ToList();
            ViewBag.data = officesList;
            return View();
        }
        [HttpPost]
        public IActionResult AddInstructor(Instructor obj)
        {
            if (ModelState.IsValid)
            {
                _context.Add(obj);
                _context.SaveChanges();

                // Update Office status 
                var OfficeId = obj.OfficeId;
                var GetOffice = _context.Offices.FirstOrDefault(x => x.Id == OfficeId);
                GetOffice.OfficeEnabled = false;
                _context.Update(GetOffice);
                _context.SaveChanges();
                TempData["notify"] = "Instructor Added Successfully";

                return RedirectToAction("index");
            }
            else
            {
                List<Office> officesList = _context.Offices.Where(x => x.OfficeEnabled == true).ToList();
                ViewBag.data = officesList;
            }

            return View();
            
        }

        public IActionResult Edit(int Id)
        {
            var Instructor = _context.Instructors.FirstOrDefault(x => x.Id == Id);

            return View(Instructor);

        }

        [HttpPost]
        public IActionResult Edit(Instructor obj)
        {
            _context.Update(obj);
            _context.SaveChanges();
            TempData["notify"] = "Instructor Update Successfully";

            return RedirectToAction("index");
        }


        public IActionResult Delete(int Id)
        {
            var Instructor = _context.Instructors.FirstOrDefault(x => x.Id == Id);

            return View(Instructor);

        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int Id)
        {
            var Instructor = _context.Instructors.Single(x => x.Id == Id);
            var OfficeId = Instructor.OfficeId;
            _context.Remove(Instructor);
            _context.SaveChanges();

            // Update Office status 
            
            var GetOffice = _context.Offices.Single(x => x.Id == OfficeId);
            GetOffice.OfficeEnabled = true;
            _context.Update(GetOffice);
            _context.SaveChanges();
            TempData["notify"] = "Instructor Delete Successfully";

            return RedirectToAction("index");
        }


    }
}

Academics/Controllers/ParticipantController.cs
using Academic.DataAccess;
using Academics.Models;
using Academics.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Academics.Controllers
{
    public class ParticipantController : Controller
    {
        private readonly AppDbContext _context;
        public ParticipantController()
        {

            var context = new AppDbContext();
            _context = context;

        }

        public IActionResult Index(int currentPage=1)
        {
            IEnumerable<Participant> Participant = _context.Particpants.ToList();

            var empData = new PaginatedList<Participant>();

            int totalRecords = Participant.Count();
            int pageSize = 100;
            int totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);
            Participant = Participant.Skip((currentPage - 1) * pageSize).Take(pageSize);
          
            empData.Entity = Participant;
            empData.CurrentPage = currentPage;
            empData.TotalPages = totalPages;
            empData.PageSize = pageSize;

            

            return View(empData);
          
        }
        
        public IActionResult Add()
        {
            return View(new ParticipantsVM());
        }

        [HttpPost]
        public IActionResult Add(ParticipantsVM obj)
        {
            if (obj.Individual.Id != 0)
            {
                _context.Individuals.Add(obj.Individual);
            }
            else if (obj.Corporate.Id != 0)
            {
                _context.Corporates.Add(obj.Corporate);
            }
            
            _context.SaveChanges();
            TempData["notify"] = "Participant Added Successfully";

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            
            var enrollment = _context.Enrollments.Where(x => x.ParticipantId == id);

            var individual = _context.Individuals.Include(x=>x.Sections).ThenInclude(x=>x.Schedule).FirstOrDefault(x => x.Id == id);

            var corporate = _context.Corporates.Include(x => x.Sections).ThenInclude(x => x.Schedule).FirstOrDefault(x => x.Id == id);

            var section =_context.Sections.ToList();

            var participantVM = new ParticipantsVM
            {
                Individual = individual,
                Corporate = corporate,
                Sections = section,
                Enrollment = new Enrollment()
      
            };



            return View(participantVM);
        }
        [HttpPost]
        [ActionName("Details")]
        public IActionResult Enrollment(ParticipantsVM obj)
        {
            if(obj != null)
            {
                _context.Enrollments.Add(obj.Enrollment);
                _context.SaveChanges();
                TempData["notify"] = "Registering Participant Successfully";
            }
            int ParticipantId = obj.Enrollment.ParticipantId;

            var individual = _context.Individuals.Include(x => x.Sections).ThenInclude(x => x.Schedule).FirstOrDefault(x => x.Id == ParticipantId);

            var corporate = _context.Corporates.Include(x => x.Sections).ThenInclude(x => x.Schedule).FirstOrDefault(x => x.Id == ParticipantId);

            var section = _context.Sections.ToList();

            var participantVM = new ParticipantsVM
            {
                Individual = individual,
                Corporate = corporate,
                Sections = section,

            };


            return View(participantVM);
        }


        public IActionResult Edit(int Id)
        {

            var Participates = new ParticipantsVM
            {
                Individual = _context.Individuals.FirstOrDefault(x => x.Id == Id),
                Corporate = _context.Corporates.FirstOrDefault(x => x.Id == Id)
            };


            return View(Participates);
        }

        [HttpPost]
        public IActionResult Edit(ParticipantsVM obj)
        {
            if(obj.Individual != null)
            {
                _context.Update(obj.Individual);
            }
            else if (obj.Corporate != null) 
            {
                _context.Update(obj.Corporate);
            }
           
            _context.SaveChanges();
            TempData["notify"] = "Participant Updated Successfully";

            return RedirectToAction("index");
        }

        public IActionResult Delete(int Id)
        {

            var Participates = new ParticipantsVM
            {
                Individual = _context.Individuals.FirstOrDefault(x => x.Id == Id),
                Corporate = _context.Corporates.FirstOrDefault(x => x.Id == Id)
            };


            return View(Participates);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int Id)
        {
            var Individual = _context.Individuals.FirstOrDefault(x => x.Id == Id);
            var Corporate = _context.Corporates.FirstOrDefault(x => x.Id == Id);

            if (Individual != null)
            {
                _context.Remove(Individual);
            }
            else if (Corporate != null)
            {
                _context.Remove(Corporate);
            }

            _context.SaveChanges();
            TempData["notify"] = "Participant Deleted Successfully";

            return RedirectToAction("index");
        }
    }
}

Academics/Controllers/SectionController.cs
using Academic.DataAccess;
using Academics.Models;
using Academics.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;



namespace Academics.Controllers
{
    public class SectionController : Controller
    {
        private readonly AppDbContext _context;
        public SectionController()
        {

            var context = new AppDbContext();
            _context = context;

        }
        public IActionResult Index(int currentPage=1)
        {
            IEnumerable<Section> sections = _context.Sections.Include(c=>c.Course)
                .Include(i=>i.Instructor).Include(s=>s.Schedule).ToList();

            var empData = new PaginatedList<Section>();

            int totalRecords = sections.Count();
            int pageSize = 10;
            int totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);
            sections = sections.Skip((currentPage - 1) * pageSize).Take(pageSize);

            empData.Entity = sections;
            empData.CurrentPage = currentPage;
            empData.TotalPages = totalPages;
            empData.PageSize = pageSize;


            return View(empData);
          
        }

        public IActionResult Add()
        {
            var sectionVM = new SectionVM
            {
                Section = new Section(),
                Course=_context.Courses.ToList(),
                Instructors=_context.Instructors.ToList(),  
                Schedules=_context.Schedules.ToList(),  
            };
            return View(sectionVM);
        }

        [HttpPost]
        public IActionResult Add(SectionVM sectionVM)
        {
            if(sectionVM.Section != null)
            {
                _context.Add(sectionVM.Section);
                _context.SaveChanges();
                TempData["notify"] = "Section Added Successfully";

            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int Id)
        {
            if(Id != 0)
            {
                var section = _context.Sections.FirstOrDefault(x => x.Id == Id);
                var sectionVM = new SectionVM
                {
                    Section = section,
                    Course = _context.Courses.ToList(),
                    Instructors = _context.Instructors.ToList(),
                    Schedules = _context.Schedules.ToList(),
                };
                return View(sectionVM);
            }

            return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(SectionVM obj)
        {
            if (obj.Section != null)
            {
                _context.Update(obj.Section);
                _context.SaveChanges();
                TempData["notify"] = "Section Updated Successfully";

            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            if (Id != 0)
            {
                var section = _context.Sections.Include(c => c.Course)
                .Include(i => i.Instructor).Include(s => s.Schedule).FirstOrDefault(y => y.Id == Id);

                return View(section);
            }
            else
            {
                return NotFound();
            }
        }


        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int Id)
        {
            if(Id != 0)
            {
                var section = _context.Sections.FirstOrDefault(y => y.Id == Id);
                if (section != null)
                {
                    _context.Remove(section);
                    _context.SaveChanges();
                    TempData["notify"] = "Section Deleted Successfully";

                }

            }
            else
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Details(int Id,int participatnId,string flag="")
        {
            // The flag is for determined if the request for registering participant or delete the participant 

            if (participatnId != 0)
            {
                if (flag == "register")
                {
                    var enrollment = new Enrollment
                    {
                        ParticipantId = participatnId,
                        SectionId = Id,
                    };
                    _context.Add(enrollment);
                    _context.SaveChanges();
                    TempData["notify"] = "Register Participant Successfully";
                }
                if (flag == "remove")
                {
                    var enrollment = _context.Enrollments.Where(s => s.SectionId == Id).ToList();

                    foreach (var item in enrollment)
                    {
                        if (item.ParticipantId == participatnId)
                        {
                            _context.Remove(item);
                            _context.SaveChanges();
                            TempData["notify"] = "Remove Participant Successfully";
                        }
                    }
                }
                
            }
            if(Id!=0)
            {
                var section = _context.Sections.Include(c => c.Course)
                    .Include(i=>i.Instructor).Include(s => s.Schedule)
                    .Include(p=>p.Participants)
                    .FirstOrDefault(x => x.Id == Id);
                return View(section);
            }
            else
            {
               return NotFound();
            }
        }
    }
}

Academics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Academics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Academics.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Academics</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Office" asp-action="Index">Offices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Participant" asp-action="Index">Participants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Section" asp-action="Index">Sections</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotifyPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Academics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/snippets.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Academics/Views/Shared/_NotifyPartial.cshtml
@{
    if (TempData["notify"] != null)
    {
        <div id="liveToast" class="toast text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex ">
                <div class="toast-body">
                    @TempData["notify"]
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div> 
    }
}